Repository jupyterlab/retrolab, pull requests merged in 2021-11, with the labels that each got.

#266 Automated Changelog Entry for 0.3.12 on main
  CHANGELOG.md
Labels: documentation

#265 Ensure `@retrolab` settings
  .gitignore
  CONTRIBUTING.md
  app/index.js
  app/webpack.config.js
  binder/postBuild
  buildutils/src/develop.ts
  package.json
  packages/application-extension/package.json
  packages/application-extension/schema/top.json
  packages/application-extension/src/index.ts
  pyproject.toml
  setup.cfg
  setup.py
Labels: enhancement

#269 edits to aid in navigation of Readme.md
  README.md
Labels: documentation

#271 Fix typos in readme
  RELEASE.md
Labels: documentation

#273 Update UI Tests to use Galata
  .github/actions/build-dist/action.yml
  .github/workflows/build.yml
  .github/workflows/ui-tests.yml
  .gitignore
  app/package.json
  app/playwright.config.ts
  app/test/notebook.spec.ts
  app/test/tree.spec.ts
  app/test/utils.ts
  package.json
  pyproject.toml
  tsconfig.eslint.json
  ui-tests/package.json
  ui-tests/playwright.config.ts
  ui-tests/test/fixtures.ts
  ui-tests/test/jupyter_server_config.py
  ui-tests/test/notebook.spec.ts
  ui-tests/test/smoke.spec.ts
  ui-tests/test/tree.spec.ts
  ui-tests/tsconfig.test.json
  ui-tests/yarn.lock
  yarn.lock
Labels: maintenance

#278 Update testing docs
  CONTRIBUTING.md
Labels: documentation

#281 Add UI test to check the retrolab settings are persisted
  ui-tests/test/settings.spec.ts
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: maintenance

#284 Fix plugin ids in the notebook extension
  packages/notebook-extension/src/index.ts
Labels: maintenance

#280 Fix handling of the MathJax URL to render Latex
  retrolab/app.py
Labels: bug

#285 Automated Changelog Entry for 0.3.13 on main
  CHANGELOG.md
Labels: documentation

#289 Improve menus
  packages/application-extension/schema/menus.json
  packages/application-extension/src/index.ts
  packages/tree-extension/src/index.ts
  ui-tests/test/editor.spec.ts
  ui-tests/test/menus.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-new-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-new-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-theme-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-theme-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/notebooks/empty.ipynb
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
Labels: enhancement

#291 Enforce labels on PRs
  .github/workflows/enforce-labels.yml
Labels: maintenance

#293 Remove unused build:test task in app
  .gitignore
  app/package.json
Labels: maintenance

#292 Add UI test for the mobile layout
  packages/application-extension/src/index.ts
  packages/application/src/app.ts
  packages/notebook-extension/src/index.ts
  ui-tests/test/jupyter_server_config.py
  ui-tests/test/mobile.spec.ts
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts
Labels: maintenance
