Repository jupyterlab/retrolab, pull requests merged in 2021-09, with the labels that each got.

#203 Add expose add in browser for galata
  app/index.js
  retrolab/app.py
Labels: enhancement

#202 Route on file browser navigation
  app/test/tree.spec.ts
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
  retrolab/app.py
Labels: enhancement

#204 Automated Changelog Entry for 0.3.3 on main
  CHANGELOG.md
Labels: documentation

#158 Add an 'interface switcher' to the toolbar
  packages/lab-extension/package.json
  packages/lab-extension/src/index.ts
  packages/lab-extension/tsconfig.json
Labels: enhancement

#206 Automated Changelog Entry for 0.3.4 on main
  CHANGELOG.md
Labels: documentation

#207 Adopt the Jupyter Releaser
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/release.yml
  package.json
Labels: maintenance

#208 Show path in the console tab title
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
Labels: enhancement

#210 Remove release-npm script
  .github/workflows/buildutils.yml
  buildutils/src/release-npm.ts
  package.json
Labels: maintenance

#211 Automated Changelog Entry for 0.3.5 on main
  CHANGELOG.md
Labels: documentation

#212 Fix handling of skip-commit
  buildutils/src/release-bump.ts
  buildutils/src/release-patch.ts
Labels: bug

#216 Build prod assets on release
  package.json
Labels: maintenance

#220 Default clean script to clean the lab extension
  package.json
  packages/lab-extension/package.json
Labels: maintenance

#221 Fix clean:static to not clean the console favicon
  app/package.json
Labels: bug

#223 Update RELEASE.md to mention the Jupyter Releaser
  RELEASE.md
Labels: documentation

#224 Simplify bump version script
  .github/workflows/check-release.yml
  buildutils/src/release-bump.ts
Labels: maintenance

#229 Add support for translation
  app/index.js
  app/package.json
  binder/environment.yml
  packages/application-extension/src/index.ts
  packages/help-extension/package.json
  packages/help-extension/src/index.tsx
  packages/lab-extension/src/index.ts
  packages/notebook-extension/package.json
  packages/notebook-extension/src/index.ts
  packages/tree-extension/src/index.ts
  yarn.lock
Labels: enhancement

#230 Add a Binder section to the readme
  README.md
Labels: documentation

#232 Fix handling of `--skip-commit`
  buildutils/src/release-bump.ts
Labels: maintenance

#236 Update link to the stable Binder
  README.md
Labels: documentation

#237 Add missing translations to help extension
  packages/help-extension/src/index.tsx
Labels: enhancement
