Repository jupyterlab/retrolab, pull requests merged in 2021-12, with the labels that each got.

#295 Use `maintainer-tools` base setup action
  .github/actions/build-dist/action.yml
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
  .github/workflows/check-release.yml
Labels: maintenance

#296 Strip .ipynb extension for display in header and tab title
  packages/application-extension/src/index.ts
  ui-tests/test/notebook.spec.ts
Labels: enhancement

#301 Switch to `maintainer-tools` action for Binder on PR
  .github/workflows/binder.yml
Labels: maintenance

#304 Bump playwright version in package.json
  app/package.json
  yarn.lock
Labels: maintenance

#307 Remove `playwright` dependency from the `app` folder
  app/package.json
  yarn.lock
Labels: maintenance

#309 Interface switcher menu
  packages/lab-extension/package.json
  packages/lab-extension/src/index.ts
  packages/lab-extension/tsconfig.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
Labels: enhancement

#310 add alt text together during the 2021 diy a11y workshop (#1)
  README.md
Labels: documentation

#294 Add extension for document-scoped search
  app/index.js
  app/package.json
  packages/_metapackage/package.json
  packages/_metapackage/src/index.ts
  packages/_metapackage/tsconfig.json
  packages/documentsearch-extension/package.json
  packages/documentsearch-extension/src/index.ts
  packages/documentsearch-extension/style/base.css
  packages/documentsearch-extension/style/index.css
  packages/documentsearch-extension/style/index.js
  packages/documentsearch-extension/tsconfig.json
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  yarn.lock
Labels: enhancement

#312 Automated Changelog Entry for 0.3.14 on main
  CHANGELOG.md
Labels: documentation
