Repository jupyterlab/retrolab, pull requests merged in 2022-01, with the labels that each got.

#315 Fix handling of the Python version in the release scripts
  buildutils/src/release-bump.ts
  buildutils/src/release-patch.ts
  buildutils/src/utils.ts
Labels: maintenance

#288 Enable auto scrolling for outputs by default
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/notebook-extension/schema/scroll-output.json
  packages/notebook-extension/src/index.ts
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/ui-components/package.json
  retrolab/__init__.py
  retrolab/serverextension.py
  ui-tests/test/mobile.spec.ts
  ui-tests/test/notebook.spec.ts
  ui-tests/test/notebooks/autoscroll.ipynb
  ui-tests/test/utils.ts
  yarn.lock
Labels: enhancement

#316 Automated Changelog Entry for 0.3.15 on main
  CHANGELOG.md
Labels: documentation

#318 Remove allsettled polyfill
  app/index.js
Labels: maintenance

#321 Update to the `@jupyterlab` 3.2.6 packages
  app/package.json
  buildutils/package.json
  package.json
  packages/application-extension/package.json
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/tree-extension/package.json
  packages/tree-extension/src/index.ts
  packages/ui-components/package.json
  yarn.lock
Labels: maintenance

#322 Automated Changelog Entry for 0.3.16 on main
  CHANGELOG.md
Labels: documentation

#319 Update to JupyterLab 4.0 alpha
  .github/workflows/build.yml
  .github/workflows/buildutils.yml
  app/index.js
  app/package.json
  binder/postBuild
  buildutils/package.json
  jupyter_config.json
  package.json
  packages/application-extension/package.json
  packages/application-extension/src/index.ts
  packages/application/package.json
  packages/console-extension/package.json
  packages/docmanager-extension/package.json
  packages/documentsearch-extension/package.json
  packages/help-extension/package.json
  packages/lab-extension/package.json
  packages/notebook-extension/package.json
  packages/terminal-extension/package.json
  packages/terminal-extension/src/index.ts
  packages/tree-extension/package.json
  packages/ui-components/package.json
  pyproject.toml
  setup.cfg
  ui-tests/package.json
  ui-tests/test/menus.spec.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-edit-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-new-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-file-new-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-help-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-kernel-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-theme-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-settings-theme-firefox-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-view-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/notebook-firefox-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-chromium-linux.png
  ui-tests/test/mobile.spec.ts-snapshots/tree-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-hidden-firefox-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-chromium-linux.png
  ui-tests/test/settings.spec.ts-snapshots/top-visible-firefox-linux.png
  ui-tests/test/smoke.spec.ts
  ui-tests/test/utils.ts
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#326 Automated Changelog Entry for 0.4.0a0 on main
  CHANGELOG.md
Labels: documentation

#330 Add `Accel Enter` shortcut to execute a cell
  packages/notebook-extension/src/index.ts
Labels: enhancement

#328 Switch cell type from the cell menu
  packages/notebook-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-firefox-linux.png
Labels: enhancement

#333 Backport PR #330 on branch 0.3.x (Add `Accel Enter` shortcut to execute a cell)
  packages/notebook-extension/src/index.ts
Labels: enhancement

#334 Backport PR #328: Switch cell type from the cell menu
  packages/notebook-extension/src/index.ts
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-chromium-linux.png
  ui-tests/test/menus.spec.ts-snapshots/opened-menu-run-firefox-linux.png
Labels: enhancement

#335 Automated Changelog Entry for 0.3.17 on 0.3.x
  CHANGELOG.md
Labels: documentation

#336 Automated Changelog Entry Forward Ported from v0.3.17
  CHANGELOG.md
Labels: documentation

#337 Add `@jupyterlab/notebook-extension:export` plugin
  app/index.js
Labels: bug

#342 Automated Changelog Entry for 0.3.18 on 0.3.x
  CHANGELOG.md
Labels: documentation

#343 Automated Changelog Entry Forward Ported from v0.3.18
  CHANGELOG.md
Labels: documentation
